/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args){
        System.out.print("Let's change the code now!");
        System.out.print("This is what I do!");
    }
}
